name: gemini_chat
description: "Chat application with Google Gemini AI model."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.4
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  markdown_widget: ^2.3.2+2
  image_picker: ^1.0.5
  path: ^1.8.3
  flutter_screenutil: ^5.9.0
  async: ^2.11.0
  desktop_window: ^0.4.0
  url_launcher: ^6.2.6
  http: ^1.2.1
  flutter_resizable_container: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  macos:
    generate: true
  web:
    generate: true
  windows:
    generate: true
  image_path: "assets/images/app_icon.png"
