name: geminichat deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.1"
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: ./build/web
      - name: Add CNAME file
        run: echo ${{ secrets.CNAME }} > ./build/web/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
